plugins {
    id "com.android.library"
}

android {
    namespace "com.shounakmulay.telephony"

    compileSdk 36

    defaultConfig {
        minSdk 23
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    sourceSets {
        main.java.srcDirs += "src/main/kotlin"
    }

    lint {
        disable "InvalidPackage"
    }
}

dependencies {
    implementation "androidx.annotation:annotation:1.7.1"
}